# Generated by Django 4.2 on 2024-07-23 09:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIASNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of FIAS node.', max_length=100)),
                ('type', models.CharField(choices=[('house', 'house'), ('street', 'street'), ('city_district', 'city_district'), ('city', 'city'), ('federal_district', 'federal_district'), ('city', 'city')], help_text='FIAS node type', max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='baza.fiasnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
